import type { Metadata } from "next";
import {
  Crimson_Pro,
  Geist,
  Newsreader,
  Playwrite_US_Trad,
  Tangerine,
} from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const playwrite = Newsreader({
  weight: ["400"],
  display: "swap",
  variable: "--font-newsreader",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${playwrite.variable} antialiased
          bg-[#131010] no-scrollbar`}
      >
        <TooltipProvider> {children}</TooltipProvider>
      </body>
    </html>
  );
}
